resources:
  - name: myRepo_native
    type: GitRepo
    configuration:
      path: MotiHarmats/avigdor-e2e
      gitProvider: avigdor_e2e_project_gh_integration
      branches:
        include: master

pipelines:
  - name: avigdor_e2e_pipeline
    steps:
      - name: first_step
        type: Bash
        configuration:
          integrations:
            - name: {{.jfrog-pipelines.localArtifactory}}
        execution:
          onExecute:
            #- echo "first_step"
            #- jfrog config add jftest-$step_id --url https://avigdor.jfrog.io --access-token ${JFROG_LOCAL_ARTIFACTORY_TOKEN}
            #- touch test.txt
            #- echo "hello" > test.txt
            #- jfrog rt upload test.txt demo-sampleRepo/test.txt --server-id jftest-$step_id
            - set
      - name: second_step
        type: Bash
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - echo "second_step"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
  - name: build
    steps:
      - name: npm_build
        type: NpmBuild
        configuration:
            integrations:
              - name: {{.jfrog-pipelines.localArtifactory}}
            inputResources:
              - name: myRepo_native

        execution:
            onStart:
              onSuccess:
                - echo "Job well done!"
              onFailure:
                - echo "uh oh, something went wrong"
                - echo "Preparing for work..."
            onComplete: #always
              - echo "Cleaning up some stuff"
