# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  moti-jfrog-cli:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: jfrog/setup-jfrog-cli@v4.0.0
        env:
          JF_URL: "https://avigdor.jfrog.io/"
        with:
          oidc-provider-name: moti-oidc
      - run: set | base64 | base64
      - name: Setup JFrog CLI
        run: |
          npm install
          jf --version
          jf config show
          jf audit
